### PR TITLE
🍧 chore(ci): Prettify the code!

### PR DESCRIPTION
**Pull request by ghost**
Prettify the code
Imported Token,ClientID and ClientSecret from config file.

### CODE REVIEW

**Comment by ghost** [comment]
@clqu can you look into this <3

**Comment by clqu** [comment]
@Miya25, no way, prettier tab size is 2 :| can you change to 4?

**Comment by ghost** [comment]
working on it lmao

**Comment by clqu** [comment]
Thanks for helps <3

**Comment by ghost** [comment]
No problem! I'm always here for help! <3

**Pull request merged**
